TECH_OWNER_KNOWLEDGE = {
    "INFRA": {
        "full_name": "Divisi Infrastruktur",
        "description": "Mengelola infrastruktur dan layanan IT perusahaan",
        "scope": "Jaringan, server & cloud, keamanan sistem, maintenance perangkat, backup & monitoring sistem",
        "used_operation": ["RunInstances", "PublicIP-In", "PublicIP-Out", "GET", "ReadCostAllocation",
                           "Hourly", "CreateVolume", "LoadBalancing:Network", "EBS:IO-Write", "EBS:IO-Read",
                           "CreateVolume-Gp3", "HeadBucket", "POST", "PutObject", "InterZone-Out",
                           "InterZone-In", "OPTIONS", "GetObject", "HEAD", "CreateVolume-Sc1",
                           "PUT", "CreateVolume-St1", "ReadACL", "CreateSnapshot", "DELETE",
                           "ReadLocation", "StandardStorage", "ReadBucketPublicAccessBlock", "ReadBucketPolicyStatus", "ReadBucketPolicy",
                           "ObjectTagCount", "DeepArchiveS3ObjectOverhead", "HeadObject", "ListBucket", "GlacierInstantRetrievalStorage",
                           "OneZoneIAStorage", "PreflightRequest", "CompleteMultipartUpload", "InitiateMultipartUpload", "ReadBucketOwnershipControls",
                           "ReadVersioningProps", "DeepArchiveStagingStorage", "GlacierS3ObjectOverhead", "GlacierStorage", "IntelligentTieringAIAStorage", "GlacierObjectOverhead", "UploadPart", "ReadBucketServerSideEncryption", "ReadAccelerate", "ReadBucketIntelligentTiering",
                           "ReadNotificationProps", "ReadLogProps", "ReadRequestPaymentProps", "ReadObjectTagging", "ReadBucketAnalytics",
                           "ReadBucketCors", "ReadBucketLifecycle", "ReadBucketInventory", "ReadBucketReplication", "WriteCostAllocation"],
        "products_handled": ["Storage",
                             "Data Transfer",
                             "Compute Instance",
                             "System Operation",
                             "Request",
                             "API Request",
                             "Load Balancer-Network",
                             "Storage Snapshot"],
        "projects_handled": ["SIMPKB", "PPG", "infra", "P2GTKMP", "SekolahPenggerak",
                             "PerlindunganPTK", "SIMPATIKA", "GuruPenggerak", "PPGPRAJAB", "PPGMUTU",
                             "DIKLATKSPS", "DiklatDIKMENDIKSUS", "Inkubasi", "CDN", "UKKJ",
                             "praktik-baik", "TAMASKA", "PSP-DIKLAT-IKM-PS", "PERSONALPTK", "MONEV",
                             "GBGTKPAUDDB", "KEMENSOS", "MASOOK", "BELMAWA", "LMSERKAM",
                             "GPK","PBS", "PPB", "dio", "GPO",
                             "PPGMUTUPPKS", "BACKUP", "UKKT", "GBP3K", "SMARTVILLAGE",
                             "eparkir", "GBGTKPAUD", "PPDB-Online", "SmartCityNavigator"]
    },
    "DIP": {
        "full_name": "Divisi Integrasi dan Pengembangan",
        "description": "Mengembangkan dan mengintegrasikan sistem/aplikasi perusahaan",
        "scope": "Pengembangan frontend & backend, UI/UX, integrasi API, testing, deployment, dan maintenance sistem",
        "used_operation": ["RunInstances", "Hourly", "InterZone-Out", "InterZone-In", "CreateVolume",
                           "RunInstances:SV003", "EBS:IO-Write", "EBS:IO-Read", "RunInstances:SV002", "CreateVolume-Gp3",
                           "PublicIP-In", "PublicIP-Out", "ReadCostAllocation", "HeadBucket", "CreateSnapshot",
                           "ReadBucketPolicyStatus", "ListBucket", "ReadACL", "ReadBucketPublicAccessBlock", "StandardStorage",
                           "ReadLocation", "ReadBucketPolicy", "GetObject", "ReadBucketOwnershipControls", "ReadVersioningProps",
                           "T4GCPUCredits"],
        "products_handled": ["Data Transfer",
                             "Storage",
                             "Compute Instance",
                             "System Operation",
                             "API Request",
                             "Storage Snapshot",
                             "CPU Credits"],
        "projects_handled": ["SIMPKB", "PPG", "SekolahPenggerak", "PPGMUTU", "PPGPRAJAB",
                             "GuruPenggerak", "Inkubasi", "CDN", "P2GTKMP", "DIKLATKSPS",
                             "UKKJ", "DiklatDIKMENDIKSUS", "PerlindunganPTK", "smkpk-rekognisi", "GBGTKPAUDDB",
                             "PERSONALPTK", "SIMPATIKA", "praktik-baik"]
    },
    "DLA": {
        "full_name": "Divisi Layanan Data dan Analitik",
        "description": "Mengelola data dan menghasilkan insight berbasis data",
        "scope": "Pemrosesan data, dashboard & reporting, analisis bisnis, AI/Machine Learning, data quality",
        "used_operation": ["RunInstances", "Hourly", "CreateDBInstance:0018", "InterZone-Out", "InterZone-In",
                           "CreateDBInstance:0016", "CreateVolume-Gp3", "EBS:IO-Write", "CreateVolume", "EBS:IO-Read",
                           "CreateDBInstance", "CreateSnapshot"],
        "products_handled": ["Data Transfer",
                             "Database Storage",
                             "Database Instance",
                             "Compute Instance",
                             "Storage",
                             "System Operation",
                             "Storage Snapshot"],
        "projects_handled": ["SIMPKB", "PPG", "Inkubasi", "SekolahPenggerak", "SIMPATIKA",
                             "infra", "PPGPRAJAB", "GuruPenggerak", "P2GTKMP", "GBGTKPAUDDB"]
    },
    "DPP": {
        "full_name": "Divisi Pengembangan dan Produk",
        "description": "Mengembangkan dan mengintegrasikan sistem/aplikasi perusahaan",
        "scope": "Pengembangan frontend & backend, UI/UX, integrasi API, testing, deployment, dan maintenance sistem",
        "used_operation": ["ReadCostAllocation", "HeadBucket", "Invoke", "ApiGatewayRequest", "CreateVolume",
                           "PutLogEvents", "InterZone-Out", "InterZone-In", "RunInstances", "Hourly",
                           "EBS:IO-Write", "EBS:IO-Read", "ReadBucketPublicAccessBlock", "ReadACL", "ReadBucketPolicyStatus",
                           "StandardStorage", "HourlyStorageMetering", "ReadBucketPolicy", "ReadLocation", "Shutdown"],
        "products_handled": ["Data Transfer",
                             "Storage",
                             "API Calls",
                             "API Request",
                             "System Operation",
                             "Compute Instance",
                             "Serverless",
                             "Data Payload",
                             "Storage Snapshot"],
        "projects_handled": ["SIMPKB", "DiklatDIKMENDIKSUS", "SIMPATIKA", "MASOOK", "PPG"]
    },
    "Minova": {
        "full_name": "PT Mitra Inovasi Jayantara (Vendor/Partner)",
        "description": "Perusahaan mitra TIK yang fokus pada pengembangan layanan Software as a Service (SaaS) berskala nasional untuk sektor pendidikan dan pemerintahan",
        "scope": "Pengembangan aplikasi cloud (SaaS), pengelolaan infrastruktur data storage, dan manajemen backup/snapshot (EBS) untuk proyek aplikasi eksternal.",
        "used_operation": ["CreateVolume", "EBS:IO-Read", "EBS:IO-Write", "CreateSnapshot"],
        "products_handled": ["Storage", "System Operation", "Storage Snapshot"],
        "projects_handled": ["GuruPenggerak", "UKKJ", "P2GTMP"]
    },
    "DAK": {
        "full_name": "Divisi Administrasi dan Keuangan",
        "description": "Mengelola administrasi, keuangan, dan sumber daya perusahaan",
        "scope": "Keuangan & budgeting, HR & payroll, legal & perizinan, aset & inventaris, pajak & compliance",
        "used_operation": ["RunInstances", "Hourly"],
        "products_handled": ["Compute Instance"],
        "projects_handled": ["infra"]
    }
}